import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <nav className='flex justify-center px-6 py-3 bg-emerald-600'>
          <Link
            href='/'
            className='mr-6 uppercase duration-300	 hover:text-sky-700'
          >
            Main site
          </Link>
          <Link
            href='/docLearn'
            className='w-28	mr-6 uppercase text-center rounded-xl	duration-300 hover:text-sky-700 hover:bg-cyan-50'
          >
            Doc Learn
          </Link>
          <Link
            href='/tutorialLearn'
            className='uppercase duration-300	 hover:text-sky-700'
          >
            Tutorial Learn
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
